# Generated by Django 5.2.1 on 2025-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
